# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MonParcellaire
                                 A QGIS plugin
 Manage your parcels
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-12
        copyright            : (C) 2020 by jhemmi.eu
        email                : jean@jhemmi.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MonParcellaire class from file MonParcellaire.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mon_parcellaire import MonParcellaire
    return MonParcellaire(iface)
