# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/jean/DATA/GIS/SCRIPT/QGIS/mon_parcellaire/mon_parcellaire_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MonParcellaireDockWidgetBase(object):
    def setupUi(self, MonParcellaireDockWidgetBase):
        MonParcellaireDockWidgetBase.setObjectName("MonParcellaireDockWidgetBase")
        MonParcellaireDockWidgetBase.resize(474, 335)
        font = QtGui.QFont()
        font.setPointSize(10)
        MonParcellaireDockWidgetBase.setFont(font)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_Parametres = QtWidgets.QWidget()
        self.tab_Parametres.setObjectName("tab_Parametres")
        self.FrequenceSauvegarde_comboBox = QtWidgets.QComboBox(self.tab_Parametres)
        self.FrequenceSauvegarde_comboBox.setGeometry(QtCore.QRect(170, 90, 181, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrequenceSauvegarde_comboBox.sizePolicy().hasHeightForWidth())
        self.FrequenceSauvegarde_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FrequenceSauvegarde_comboBox.setFont(font)
        self.FrequenceSauvegarde_comboBox.setObjectName("FrequenceSauvegarde_comboBox")
        self.label_Referentiel = QtWidgets.QLabel(self.tab_Parametres)
        self.label_Referentiel.setGeometry(QtCore.QRect(11, 60, 121, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Referentiel.sizePolicy().hasHeightForWidth())
        self.label_Referentiel.setSizePolicy(sizePolicy)
        self.label_Referentiel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Referentiel.setFont(font)
        self.label_Referentiel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Referentiel.setObjectName("label_Referentiel")
        self.Repertoire_lineEdit = QtWidgets.QLineEdit(self.tab_Parametres)
        self.Repertoire_lineEdit.setGeometry(QtCore.QRect(130, 60, 201, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Repertoire_lineEdit.sizePolicy().hasHeightForWidth())
        self.Repertoire_lineEdit.setSizePolicy(sizePolicy)
        self.Repertoire_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.Repertoire_lineEdit.setFont(font)
        self.Repertoire_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Repertoire_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Repertoire_lineEdit.setStyleSheet("")
        self.Repertoire_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Repertoire_lineEdit.setObjectName("Repertoire_lineEdit")
        self.label_FrequenceSauvegarde = QtWidgets.QLabel(self.tab_Parametres)
        self.label_FrequenceSauvegarde.setGeometry(QtCore.QRect(10, 90, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_FrequenceSauvegarde.setFont(font)
        self.label_FrequenceSauvegarde.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_FrequenceSauvegarde.setObjectName("label_FrequenceSauvegarde")
        self.Voir_checkBox = QtWidgets.QCheckBox(self.tab_Parametres)
        self.Voir_checkBox.setGeometry(QtCore.QRect(10, 20, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Voir_checkBox.setFont(font)
        self.Voir_checkBox.setObjectName("Voir_checkBox")
        self.tabWidget.addTab(self.tab_Parametres, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MonParcellaireDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(MonParcellaireDockWidgetBase)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MonParcellaireDockWidgetBase)

    def retranslateUi(self, MonParcellaireDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        MonParcellaireDockWidgetBase.setWindowTitle(_translate("MonParcellaireDockWidgetBase", "Mon Parcellaire V0.0.1 -  jhemmi.eu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MonParcellaireDockWidgetBase", "Tab 1"))
        self.label_Referentiel.setText(_translate("MonParcellaireDockWidgetBase", "Référentiel TOM"))
        self.Repertoire_lineEdit.setToolTip(_translate("MonParcellaireDockWidgetBase", "Chemin vers votre référentiel (par exemple C:/SIG/TOM)"))
        self.label_FrequenceSauvegarde.setText(_translate("MonParcellaireDockWidgetBase", "Sauvegarde référentiel"))
        self.Voir_checkBox.setText(_translate("MonParcellaireDockWidgetBase", "Toujours voir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Parametres), _translate("MonParcellaireDockWidgetBase", "⚙️"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MonParcellaireDockWidgetBase = QtWidgets.QDockWidget()
    ui = Ui_MonParcellaireDockWidgetBase()
    ui.setupUi(MonParcellaireDockWidgetBase)
    MonParcellaireDockWidgetBase.show()
    sys.exit(app.exec_())

